# Generated by Django 4.2.5 on 2023-10-19 23:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0016_alter_empleados_nombre_alter_empleados_puesto'),
    ]

    operations = [
        migrations.CreateModel(
            name='prestamos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Monto', models.IntegerField()),
                ('TipoPago', models.CharField(max_length=50)),
                ('FechaLimite', models.DateField()),
                ('carrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sitio.carrito')),
            ],
        ),
    ]
