# Generated by Django 4.2.5 on 2023-10-19 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0017_prestamos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prestamos',
            name='carrito',
        ),
    ]
