# Generated by Django 4.2.5 on 2023-10-19 23:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0019_alter_prestamos_tipopago'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamos',
            name='prestamo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sitio.carrito'),
        ),
    ]
