# Generated by Django 4.1.5 on 2023-11-13 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0021_alter_carrito_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prestamos',
            name='prestamo',
        ),
    ]
