# Generated by Django 4.1.5 on 2023-11-13 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0022_remove_prestamos_prestamo'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamos',
            name='nombre',
            field=models.CharField(default='Nombre predeterminado', max_length=100),
        ),
    ]
