# Generated by Django 4.2.7 on 2023-11-16 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0024_perfilusuario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PerfilUsuario',
        ),
    ]
